-- Generated by SQL Maestro for MySQL. Release date 9/15/2008
-- 4/10/2014 9:09:37 PM
-- ----------------------------------
-- Alias: mindsharp at localhost
-- Database name: mindsharp
-- Host: localhost
-- Port number: 3306
-- User name: root
-- Server: 5.1.43-community
-- Session ID: 1
-- Character set: latin1
-- Collation: latin1_swedish_ci
-- Client encoding: utf8


SET FOREIGN_KEY_CHECKS=0;

CREATE DATABASE `mindsharp`
  CHARACTER SET `latin1`
  COLLATE `latin1_swedish_ci`;

USE `mindsharp`;

/* Tables */
CREATE TABLE `gameresults` (
  `seq`                  int AUTO_INCREMENT NOT NULL,
  `userseq`              int,
  `gameseq`              int,
  `dated`                datetime,
  `score`                int,
  `correct`              int,
  `levels`               int,
  `totalattempts`        int,
  `timeplayedseconds`    int,
  `opportunities`        int,
  `accuratepercent`      int,
  `reactiontimeseconds`  int,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB
  CHARACTER SET `utf8` COLLATE `utf8_unicode_ci`;

CREATE TABLE `games` (
  `seq`          int(255) NOT NULL,
  `name`         varchar(100) NOT NULL,
  `path`         varchar(200) NOT NULL,
  `isactive`     tinyint(1) NOT NULL,
  `isdelete`     tinyint(1) NOT NULL,
  `isfree`       tinyint(1),
  `extra`        varchar(1000) NOT NULL,
  `skilltype`    varchar(20),
  `description`  varchar(2000),
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB
  CHARACTER SET `utf8` COLLATE `utf8_unicode_ci`;

CREATE TABLE `gametags` (
  `gameseq`  int NOT NULL,
  `tagseq`   int NOT NULL,
  PRIMARY KEY (`gameseq`, `tagseq`)
) ENGINE = InnoDB
  CHARACTER SET `utf8` COLLATE `utf8_unicode_ci`;

CREATE TABLE `organizations` (
  `seq`         bigint AUTO_INCREMENT NOT NULL,
  `orgtype`     varchar(20),
  `orgname`     varchar(256),
  `orgaddress`  varchar(500),
  `orgstate`    varchar(100),
  `orgcountry`  varchar(100),
  PRIMARY KEY (`seq`)
) ENGINE = MyISAM
  CHARACTER SET `utf8` COLLATE `utf8_unicode_ci`;

CREATE TABLE `promotions` (
  `seq`                int AUTO_INCREMENT NOT NULL,
  `code`               varchar(20),
  `description`        varchar(500),
  `freegames`          varchar(100),
  `orgseq`             int,
  `createdate`         datetime,
  `expirydate`         datetime,
  `gamesvaliditydays`  int,
  PRIMARY KEY (`seq`)
) ENGINE = MyISAM
  CHARACTER SET `utf8` COLLATE `utf8_unicode_ci`;

CREATE TABLE `tags` (
  `seq`  int AUTO_INCREMENT NOT NULL,
  `tag`  varchar(120) NOT NULL,
  PRIMARY KEY (`seq`)
) ENGINE = InnoDB
  CHARACTER SET `utf8` COLLATE `utf8_unicode_ci`;

CREATE TABLE `userbadges` (
  `seq`      int AUTO_INCREMENT NOT NULL,
  `userseq`  bigint,
  `badge`    varchar(20) CHARACTER SET `utf8` COLLATE `utf8_general_ci`,
  `gameseq`  int,
  `date`     datetime,
  PRIMARY KEY (`seq`)
) ENGINE = MyISAM;

CREATE TABLE `usergames` (
  `seq`             int AUTO_INCREMENT NOT NULL,
  `userseq`         int NOT NULL,
  `gameseq`         int NOT NULL,
  `enrollmentdate`  datetime NOT NULL,
  `validtilldate`   datetime NOT NULL,
  PRIMARY KEY (`seq`)
) ENGINE = MyISAM
  CHARACTER SET `utf8` COLLATE `utf8_unicode_ci`;

CREATE TABLE `users` (
  `seq`            int AUTO_INCREMENT NOT NULL,
  `emailid`        varchar(256) NOT NULL,
  `username`       varchar(100) NOT NULL,
  `password`       varchar(100) NOT NULL,
  `fullname`       varchar(500),
  `mobile`         varchar(20),
  `country`        varchar(100),
  `signupdate`     date,
  `lastlogindate`  datetime,
  `isactive`       smallint DEFAULT '1',
  `address`        varchar(500),
  `islimited`      tinyint,
  `orgseq`         int,
  `myskills`       text NOT NULL,
  `imgpath`        varchar(100) COLLATE `utf8_general_ci`,
  `imagename`      varchar(100) COLLATE `utf8_general_ci`,
  PRIMARY KEY (`seq`)
) ENGINE = MyISAM
  CHARACTER SET `utf8` COLLATE `utf8_unicode_ci`;

/* Indexes */
CREATE UNIQUE INDEX `code`
  ON `promotions`
  (`code`);

CREATE UNIQUE INDEX `unique`
  ON `tags`
  (`tag`);

/* Data for table "gameresults" */
INSERT INTO `gameresults` (`seq`, `userseq`, `gameseq`, `dated`, `score`, `correct`, `levels`, `totalattempts`, `timeplayedseconds`, `opportunities`, `accuratepercent`, `reactiontimeseconds`) VALUES (1, 1, 5, '2012-11-05 01:31:27', 375, 15, 0, 27, 45104, 0, 13, 0);
INSERT INTO `gameresults` (`seq`, `userseq`, `gameseq`, `dated`, `score`, `correct`, `levels`, `totalattempts`, `timeplayedseconds`, `opportunities`, `accuratepercent`, `reactiontimeseconds`) VALUES (2, 1, 4, '2012-11-07 02:11:21', 2200, 19, 3, 26, 45000, 0, 84, 0);
INSERT INTO `gameresults` (`seq`, `userseq`, `gameseq`, `dated`, `score`, `correct`, `levels`, `totalattempts`, `timeplayedseconds`, `opportunities`, `accuratepercent`, `reactiontimeseconds`) VALUES (3, 1, 5, '2012-11-07 02:15:13', 275, 11, 0, 22, 45036, 0, 12, 0);
INSERT INTO `gameresults` (`seq`, `userseq`, `gameseq`, `dated`, `score`, `correct`, `levels`, `totalattempts`, `timeplayedseconds`, `opportunities`, `accuratepercent`, `reactiontimeseconds`) VALUES (4, 1, 20, '2012-11-09 08:58:50', 3122, 77, 0, 87, 185357, 0, 35, 0);
INSERT INTO `gameresults` (`seq`, `userseq`, `gameseq`, `dated`, `score`, `correct`, `levels`, `totalattempts`, `timeplayedseconds`, `opportunities`, `accuratepercent`, `reactiontimeseconds`) VALUES (5, 1, 23, '2012-11-09 09:00:01', 320, 20, 0, 28, 0, 0, 11, 0);
INSERT INTO `gameresults` (`seq`, `userseq`, `gameseq`, `dated`, `score`, `correct`, `levels`, `totalattempts`, `timeplayedseconds`, `opportunities`, `accuratepercent`, `reactiontimeseconds`) VALUES (6, 1, 23, '2012-11-09 09:00:57', 600, 56, 0, 119, 0, 0, 5, 0);
INSERT INTO `gameresults` (`seq`, `userseq`, `gameseq`, `dated`, `score`, `correct`, `levels`, `totalattempts`, `timeplayedseconds`, `opportunities`, `accuratepercent`, `reactiontimeseconds`) VALUES (7, 1, 24, '2012-11-09 09:04:00', 1070, 36, 0, 39, 0, 0, 27, 0);
INSERT INTO `gameresults` (`seq`, `userseq`, `gameseq`, `dated`, `score`, `correct`, `levels`, `totalattempts`, `timeplayedseconds`, `opportunities`, `accuratepercent`, `reactiontimeseconds`) VALUES (8, 1, 26, '2012-11-09 09:10:14', 2, 1, 1, 1, 0, 0, 2, 0);
INSERT INTO `gameresults` (`seq`, `userseq`, `gameseq`, `dated`, `score`, `correct`, `levels`, `totalattempts`, `timeplayedseconds`, `opportunities`, `accuratepercent`, `reactiontimeseconds`) VALUES (9, 3, 1, '2012-11-14 02:58:35', 334, 19, 1, 20, 97415, 0, 16, 0);
INSERT INTO `gameresults` (`seq`, `userseq`, `gameseq`, `dated`, `score`, `correct`, `levels`, `totalattempts`, `timeplayedseconds`, `opportunities`, `accuratepercent`, `reactiontimeseconds`) VALUES (10, 1, 16, '2013-06-12 19:42:54', 33, 3, 1, 3, 65158, 0, 11, 0);
INSERT INTO `gameresults` (`seq`, `userseq`, `gameseq`, `dated`, `score`, `correct`, `levels`, `totalattempts`, `timeplayedseconds`, `opportunities`, `accuratepercent`, `reactiontimeseconds`) VALUES (11, 1, 16, '2013-06-12 19:51:18', 60, 5, 1, 5, 69731, 0, 12, 0);
INSERT INTO `gameresults` (`seq`, `userseq`, `gameseq`, `dated`, `score`, `correct`, `levels`, `totalattempts`, `timeplayedseconds`, `opportunities`, `accuratepercent`, `reactiontimeseconds`) VALUES (12, 1, 16, '2013-06-12 19:57:17', 33, 4, 1, 5, 61779, 0, 6, 0);
INSERT INTO `gameresults` (`seq`, `userseq`, `gameseq`, `dated`, `score`, `correct`, `levels`, `totalattempts`, `timeplayedseconds`, `opportunities`, `accuratepercent`, `reactiontimeseconds`) VALUES (13, 1, 16, '2013-06-12 19:59:38', 46, 4, 1, 4, 59922, 0, 11, 0);
INSERT INTO `gameresults` (`seq`, `userseq`, `gameseq`, `dated`, `score`, `correct`, `levels`, `totalattempts`, `timeplayedseconds`, `opportunities`, `accuratepercent`, `reactiontimeseconds`) VALUES (14, 1, 16, '2013-06-12 21:48:52', 46, 4, 1, 5, 66235, 0, 9, 0);
INSERT INTO `gameresults` (`seq`, `userseq`, `gameseq`, `dated`, `score`, `correct`, `levels`, `totalattempts`, `timeplayedseconds`, `opportunities`, `accuratepercent`, `reactiontimeseconds`) VALUES (15, 1, 16, '2013-06-13 10:51:06', 21, 3, 1, 4, 60302, 0, 5, 0);
INSERT INTO `gameresults` (`seq`, `userseq`, `gameseq`, `dated`, `score`, `correct`, `levels`, `totalattempts`, `timeplayedseconds`, `opportunities`, `accuratepercent`, `reactiontimeseconds`) VALUES (16, 1, 16, '2013-06-13 10:54:08', 46, 4, 1, 4, 56791, 0, 11, 0);
COMMIT;


/* Data for table "games" */
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (1, 'Sleeping Superman', 'addition_storm_game\\addition_storm_game', 1, 0, 0, 'rt', 'speed', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (2, 'Focus Change', 'brain_shift_game\\brain_shift_game', 1, 0, 0, 'rt', 'flexibility', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (3, 'By the Reles', 'by_the_rules_game\\by_the_rules_game\\by_the_rules_game\\by_the_rules_game', 0, 0, 0, 'rt', 'memory', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (4, 'Tribal Board', 'chalkboard_challenge_game\\chalkboard_challenge_game', 1, 0, 0, 'rt', 'problemSolving', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (5, 'Color Confusion', 'color_match_game\\color_match_game', 1, 0, 0, 'rt', 'attention', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (6, 'Puzzle Place', 'disconnection_game\\disconnection_game', 1, 0, 0, 'rt', 'flexibility', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (7, 'Puzzle Piece', 'disillusion_game\\disillusion_game', 1, 0, 0, 'rt', 'flexibility', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (8, 'Forest Fire', 'division_storm_game\\division_storm_game', 1, 0, 0, 'rt', 'speed', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (9, 'Eagle Eye - NA', 'eagle_eye_game\\eagle_eye_game', 0, 0, 0, 'rt', 'memory', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (10, 'Familiar Faces', 'familiar_faces_game\\familiar_faces_game', 0, 0, 0, 'rt', 'memory', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (11, 'Different Direction', 'lost_in_migration_game\\lost_in_migration_game', 1, 0, 0, 'rt', 'problemSolving', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (12, 'Memory Match', 'memory_match_game\\memory_match_game', 0, 0, 0, 'rt', 'memory', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (13, 'Memory Grid', 'memory_matrix_game\\memory_matrix_game', 1, 0, 0, 'rt', 'memory', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (14, 'Bee Business', 'moneycomb_game\\moneycomb_game', 1, 0, 0, 'rt', 'memory', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (15, 'Cheeze Challenge', 'monster_garden_game\\monster_garden_game', 1, 0, 0, 'rt', 'memory', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (16, 'Kitchen Itching', 'multiplication_storm_game\\multiplication_storm_game', 1, 0, 0, 'rt', 'speed', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (17, 'Name Tags', 'name_tag_game\\name_tag_game', 1, 0, 0, 'rt', 'memory', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (18, 'Observation Tower', 'observation_tower\\observation_tower', 0, 0, 0, 'rt', 'memory', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (19, 'Feeding Fishes', 'playing_koi_game\\playing_koi_game', 1, 0, 0, 'rt', 'attention', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (20, 'Brain Drops', 'raindrops_game\\raindrops_game', 1, 0, 0, 'rt', 'speed', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (21, 'Grid Grasp', 'rotation_matrix_game\\rotation_matrix_game', 1, 0, 0, 'rt', 'memory', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (22, 'Flash Frame', 'space_junk_game\\space_junk_game', 1, 0, 0, 'rt', 'memory', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (23, 'Pattern Recognition', 'spatial_speed_match_game\\spatial_speed_match_game', 1, 0, 0, 'rt', 'speed', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (24, 'Rapid Recall', 'speed_match_game\\speed_match_game', 1, 0, 0, 'rt', 'speed', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (25, 'Snack Save', 'subtraction_storm_game\\subtraction_storm_game', 1, 0, 0, 'rt', 'speed', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (26, 'Zoo Smart', 'top_chimp_game\\top_chimp_game', 1, 0, 0, 'rt', 'problemSolving', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (27, 'Word Root', 'word_bubbles_game\\word_bubbles_game', 1, 0, 0, 'rt', 'problemSolving', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (28, 'Word Bubbles Rising', 'word_bubbles_rising_game\\word_bubbles_rising_game', 1, 0, 0, 'rt', 'problemSolving', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
INSERT INTO `games` (`seq`, `name`, `path`, `isactive`, `isdelete`, `isfree`, `extra`, `skilltype`, `description`) VALUES (29, 'Luck Logic', 'word_sort_game\\word_sort_game', 1, 0, 0, 'rt', 'problemSolving', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel arcu urna, eget venenatis nisi. Aenean luctus, magna in adipiscing tristique, lacus eros imperdiet risus, ac vestibulum augue velit sit amet felis. Aliquam erat volutpat. Pellentesque imperdiet viverra lorem eget placerat. Ut ut suscipit metus. Nam suscipit, velit non auctor consequat, enim nunc imperdiet est, et porttitor est mauris non est. Morbi quis libero sit amet sapien ullamcorper lobortis. Nullam fringilla dictum suscipit. Vestibulum in ipsum ipsum.');
COMMIT;


/* Data for table "gametags" */
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (1, 1);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (1, 2);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (4, 5);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (5, 6);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (6, 7);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (7, 1);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (8, 1);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (8, 3);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (13, 5);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (14, 7);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (15, 7);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (16, 8);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (17, 2);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (19, 4);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (20, 6);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (21, 3);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (22, 2);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (23, 3);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (24, 5);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (25, 6);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (26, 1);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (27, 5);
INSERT INTO `gametags` (`gameseq`, `tagseq`) VALUES (29, 1);
COMMIT;


/* Data for table "organizations" */
INSERT INTO `organizations` (`seq`, `orgtype`, `orgname`, `orgaddress`, `orgstate`, `orgcountry`) VALUES (1, 'college', 'Guru Nanak Institute of Management Technology', 'Model Town, Ludhiana', 'Punjab', 'India');
COMMIT;


/* Data for table "promotions" */
INSERT INTO `promotions` (`seq`, `code`, `description`, `freegames`, `orgseq`, `createdate`, `expirydate`, `gamesvaliditydays`) VALUES (1, 'MS1', 'Two free games ', '1,2', 1, '2012-11-01 00:00:00', '2012-12-31 00:00:00', 30);
INSERT INTO `promotions` (`seq`, `code`, `description`, `freegames`, `orgseq`, `createdate`, `expirydate`, `gamesvaliditydays`) VALUES (2, 'MS2', 'Two free games', '1,4', NULL, '2012-11-01 00:00:00', '2012-11-24 00:00:00', 60);
COMMIT;


/* Data for table "tags" */
INSERT INTO `tags` (`seq`, `tag`) VALUES (4, 'Estimation');
INSERT INTO `tags` (`seq`, `tag`) VALUES (2, 'Mental Math');
INSERT INTO `tags` (`seq`, `tag`) VALUES (3, 'Multitasking');
INSERT INTO `tags` (`seq`, `tag`) VALUES (1, 'Numerical Ability');
INSERT INTO `tags` (`seq`, `tag`) VALUES (5, 'Pattern Recognition');
INSERT INTO `tags` (`seq`, `tag`) VALUES (8, 'Productivity');
INSERT INTO `tags` (`seq`, `tag`) VALUES (7, 'Remembering people');
INSERT INTO `tags` (`seq`, `tag`) VALUES (6, 'Spatial Intelligence');
INSERT INTO `tags` (`seq`, `tag`) VALUES (9, 'Verbal Ability');
COMMIT;


/* Data for table "userbadges" */
INSERT INTO `userbadges` (`seq`, `userseq`, `badge`, `gameseq`, `date`) VALUES (1, 1, 'newbie', 16, '2013-06-12 21:48:52');
INSERT INTO `userbadges` (`seq`, `userseq`, `badge`, `gameseq`, `date`) VALUES (2, 1, 'starter', 16, '2013-06-13 10:54:08');
COMMIT;


/* Data for table "usergames" */
INSERT INTO `usergames` (`seq`, `userseq`, `gameseq`, `enrollmentdate`, `validtilldate`) VALUES (1, 3, 1, '2012-11-14 02:26:18', '2012-12-14 02:26:18');
INSERT INTO `usergames` (`seq`, `userseq`, `gameseq`, `enrollmentdate`, `validtilldate`) VALUES (2, 3, 2, '2012-11-14 02:26:18', '2012-12-14 02:26:18');
COMMIT;


/* Data for table "users" */
INSERT INTO `users` (`seq`, `emailid`, `username`, `password`, `fullname`, `mobile`, `country`, `signupdate`, `lastlogindate`, `isactive`, `address`, `islimited`, `orgseq`, `myskills`, `imgpath`, `imagename`) VALUES (1, 'munishsethi777@gmail.com', 'munish', 'sss', 'Munish sethi', NULL, NULL, '2012-11-14', NULL, 0, NULL, 0, 0, 'speed,problemSolving,attention,memory', NULL, '1_thumb.jpg');
INSERT INTO `users` (`seq`, `emailid`, `username`, `password`, `fullname`, `mobile`, `country`, `signupdate`, `lastlogindate`, `isactive`, `address`, `islimited`, `orgseq`, `myskills`, `imgpath`, `imagename`) VALUES (3, 'munishsethi777@gmail.com', 'munish1', 'a', 'Munish sethi', NULL, NULL, '2012-11-14', NULL, 0, NULL, 1, 1, '', NULL, NULL);
COMMIT;
